import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const instrumentsSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body
          className={`${instrumentsSans.variable} antialiased    bg-background overflow-x-hidden`}
          >

          <Navbar />
          <main className=" font-[family-name:var(--font-instrument-sans)]  space-y-40 my-container max-sm:px-3">
            {children}
          </main>
          <Footer />
        </body>
      </html>
  );
}
